info:
  type: content_page
  title: Product Landing Page Example
  path:
    alias: /examples/product-landing-page
    pathauto: 0

field_page_section:
  paragraphs:
  - paragraph_type: d_p_banner
    data:
      field_d_main_title:
        type: text
        data: Enjoy Life And Your Ride
      field_d_subtitle:
        type: text
        data: Product Landing Page Example
      field_d_image_background:
        type: image
        data: demo_car_1.jpg
      field_d_long_text:
        type: text_long
        data: <p>This page is the example of a product landing page, the showcase of a single item from your offer.
          It contains lots of high-quality photos and shows all the advantages and qualities.
          The desired reaction of the viewer is a purchase.</p>
      field_d_cta_link:
        type: cta
        data:
          link: internal:/examples/product-landing-page
          text: Buy now
  - paragraph_type: d_p_group_of_text_blocks
    data:
      field_d_main_title:
        type: text
        data: Innovation and Technology
      field_d_cta_link:
        type: cta
        data:
          link: internal:/examples/product-landing-page
          text: Take a test ride
      field_d_p_tb_block_reference:
        type: paragraph_reference
        data:
        - field_d_main_title:
            type: text
            data: Safety
          field_d_long_text:
            type: text_long
            data: <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam cursus
              tristique dui dignissim gravida.</p>
          field_d_cta_link:
            type: cta
            data:
              link: internal:/examples/product-landing-page
              text: More
        - field_d_main_title:
            type: text
            data: Engines
          field_d_long_text:
            type: text_long
            data: <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam cursus
              tristique dui dignissim gravida.</p>
          field_d_cta_link:
            type: cta
            data:
              link: internal:/examples/product-landing-page
              text: More
        - field_d_main_title:
            type: text
            data: The package
          field_d_long_text:
            type: text_long
            data: <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam cursus
              tristique dui dignissim gravida.</p>
          field_d_cta_link:
            type: cta
            data:
              link: internal:/examples/product-landing-page
              text: More
        - field_d_main_title:
            type: text
            data: Colors
          field_d_long_text:
            type: text_long
            data: <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam cursus
              tristique dui dignissim gravida.</p>
          field_d_cta_link:
            type: cta
            data:
              link: internal:/examples/product-landing-page
              text: More
        - field_d_main_title:
            type: text
            data: Drive
          field_d_long_text:
            type: text_long
            data: <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam cursus
              tristique dui dignissim gravida.</p>
          field_d_cta_link:
            type: cta
            data:
              link: internal:/examples/product-landing-page
              text: More
        - field_d_main_title:
            type: text
            data: Service
          field_d_long_text:
            type: text_long
            data: <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam cursus
              tristique dui dignissim gravida.</p>
          field_d_cta_link:
            type: cta
            data:
              link: internal:/examples/product-landing-page
              text: More


  - paragraph_type: d_p_side_image
    data:
      field_d_main_title:
        type: text
        data: Comfort when onboarding
      field_d_image_background:
        type: image
        data: demo_car_2.jpg
      field_d_p_si_image_side:
        type: text_select
        data: left
      field_d_long_text:
        type: text_long
        data: <p>Aenean feugiat dui sit amet condimentum volutpat. Cras malesuada fermentum
          felis at vulputate. In commodo nunc sed mi placerat eleifend. Morbi maximus,
          enim at sagittis lobortis, ante quam pulvinar nulla, vel gravida diam magna
          luctus mi.</p>
  - paragraph_type: d_p_side_image
    data:
      field_d_main_title:
        type: text
        data: Focus on the road
      field_d_image_background:
        type: image
        data: demo_car_5.jpg
      field_d_p_si_image_side:
        type: text_select
        data: right
      field_d_long_text:
        type: text_long
        data: <p>Aenean feugiat dui sit amet condimentum volutpat. Cras malesuada fermentum
          felis at vulputate. In commodo nunc sed mi placerat eleifend. Morbi maximus,
          enim at sagittis lobortis, ante quam pulvinar nulla, vel gravida diam magna
          luctus mi.</p>
  - paragraph_type: d_p_side_image
    data:
      field_d_main_title:
        type: text
        data: All under control
      field_d_image_background:
        type: image
        data: demo_car_6.jpg
      field_d_p_si_image_side:
        type: text_select
        data: left
      field_d_long_text:
        type: text_long
        data: <p>Aenean feugiat dui sit amet condimentum volutpat. Cras malesuada fermentum
          felis at vulputate. In commodo nunc sed mi placerat eleifend. Morbi maximus,
          enim at sagittis lobortis, ante quam pulvinar nulla, vel gravida diam magna
          luctus mi.</p>
  - paragraph_type: d_p_side_image
    data:
      field_d_main_title:
        type: text
        data: Authentic pleasure of driving
      field_d_image_background:
        type: image
        data: demo_car_7.jpg
      field_d_p_si_image_side:
        type: text_select
        data: right
      field_d_long_text:
        type: text_long
        data: <p>Aenean feugiat dui sit amet condimentum volutpat. Cras malesuada fermentum
          felis at vulputate. In commodo nunc sed mi placerat eleifend. Morbi maximus,
          enim at sagittis lobortis, ante quam pulvinar nulla, vel gravida diam magna
          luctus mi.</p>

  - paragraph_type: d_p_tiles
    data:
      field_d_image:
        type: image
        data:
        - file: demo_car_1.jpg
          alt: 2x2 Lorem / Ipsum
        - file: demo_car_2.jpg
          alt: Aenean / Feugiat
        - file: demo_car_5.jpg
          alt: Placerat / Eleifend
        - file: demo_car_6.jpg
          alt: Sagittis / Lobortis
        - file: demo_car_7.jpg
          alt: Condimentum / Pulvinar

  - paragraph_type: d_p_carousel
    data:
      field_d_number:
        type: number
        data: 1
      field_d_main_title:
        type: text
        data: Testimonials
      field_d_p_cs_item_reference:
        type: paragraph_reference
        subtype: d_p_carousel_item
        data:
        - field_d_image:
            type: image
            data:
            - file: demo_face_2.png
              alt: John Smith
          field_d_main_title:
            type: text
            data: John Smith, CEO of Cube Inc.
          field_d_long_text:
            type: text_long
            data: <p><em>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam cursus
              tristique dui dignissim gravida. Aenean feugiat dui sit amet condimentum volutpat.
              Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat.</em></p>
        - field_d_image:
            type: image
            data:
            - file: demo_face_1.png
              alt: Anna Novak
          field_d_main_title:
            type: text
            data: Anna Novak, Chief Architect of BTU
          field_d_long_text:
            type: text_long
            data: <p><em>Cras malesuada fermentum felis at vulputate. In commodo nunc sed mi placerat eleifend.
              Morbi maximus, enim at sagittis lobortis, ante quam pulvinar nulla, vel gravida diam magna mi.
              Nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt.</em></p>
        - field_d_image:
            type: image
            data:
            - file: demo_face_3.png
              alt: Zhang San
          field_d_main_title:
            type: text
            data: Zhang San, Atlantic Jetlines
          field_d_long_text:
            type: text_long
            data: <p><em>Sagittis vitae et leo duis ut diam. Id ornare arcu odio ut. Accumsan sit amet nulla facilisi
              morbi tempus iaculis urna. Nullam non nisi est sit amet facilisis magna etiam. Elementum facilisis leo
              vel fringilla est ullamcorper eget nulla facilisi. Volutpat lacus laoreet non curabitur gravida arcu.</em></p>

  - paragraph_type: d_p_text_paged
    data:
      field_d_main_title:
        type: text
        data: Perfect trip is just around the corner!
  - paragraph_type: d_p_banner
    data:
      field_d_main_title:
        type: text
        data: Your turn
      field_d_subtitle:
        type: text
        data: Schedule a test ride. It is your decision which road to take and how
          fast you go!
      field_d_image_background:
        type: image
        data: demo_car_1.jpg
      field_d_long_text:
        type: text_long
        data: ''
      field_d_cta_link:
        type: cta
        data:
          link: internal:/examples/product-landing-page
          text: Contact Us
